### ISSUE TITLE
Images not appear in DogBreeds.png

### ISSUE THREAD

**Issue by Chelseain** [Nischal-Karki-ATW/TidyTuesday#1]
Hi Nischal,

I am super interested in your plot for Feb 1st's TidyTuesday. I copied your code, downloaded three images under the same folder of the Rmd file, and tried to run. However, the three images could not appear in the saved png (I copied here) and there was no error or warning when I ran the code. Have you ever had this problem? Do you have any suggestions on it? Thank you so much for any support!
![DogBreeds](https://user-images.githubusercontent.com/49087011/153099158-10b9640f-edf9-4e53-8343-65893e01c81c.png)

Best regards,
Yiqian

**Comment by Nischal-Karki-ATW** [comment]
Hi Yiqian,
Thanks for reaching out! 
The cowplot draw_image function requires the `magick` package to be installed. 
Copied from [draw_image](https://www.rdocumentation.org/packages/cowplot/versions/1.1.1/topics/draw_image) documentation

> Requires the magick package to work, and fails gracefully if that package is not installed.

This is the only thing I can think of right now. Can you check this and let me know if the problem still persists?

**Comment by Chelseain** [comment]
> 

Hi Nischal,

That is the point - I installed the `magick` package and it works! Thank you for clarifying that.

Best,
Yiqian
